### ISSUE TITLE
Incorporate helper based solution (e.g. `{{title` )

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-title#5]
Chat with the folks maintaining [ember-page-title](https://github.com/adopted-ember-addons/ember-page-title) about merging. 

/cc @knownasilya

**Comment by knownasilya** [comment]
@rwjblue say more. Not sure what this addon does

**Comment by rwjblue** [comment]
@knownasilya - Doesn't do anything (yet), but the idea is to provide the features of both ember-page-title and ember-cli-document-title in one addon **and** get that addon added to the default `ember new` output (via an RFC).

**Comment by knownasilya** [comment]
Totally on board. Let me know what you need from me.

**Comment by Turbo87** [comment]
why not put the work into the existing addon instead of creating another one? 🤔

**Comment by rwjblue** [comment]
Sure, definitely a valid point. I prefer this name, and either way I have to work through the logic changes required to support both. I do not think the implementation will resemble the existing logic in either repo very much.
